### PR TITLE
Allow php ~8.1.0

### PR DESCRIPTION
**Pull request by fezfez**

### CODE REVIEW

**Comment by fezfez** [comment]
seem to work but need #16 before

**Comment by fezfez** [comment]
CI now working

**Review by Ocramius — CHANGES_REQUESTED** [review]
@fezfez we need the `composer.lock` file to be re-generated here

**Comment by fezfez** [comment]
@Ocramius done

**Review by Ocramius — APPROVED** [review]

**Comment by Ocramius** [comment]
Thanks @fezfez!

**Comment by fezfez** [comment]
hi @Ocramius the 2.10.0 version seem to not have the modification in it... :s

**Comment by fezfez** [comment]
it appear to be merge in 2.9.x

**Comment by Ocramius** [comment]
My bad, fixing shortly

**Comment by fezfez** [comment]
same problem on laminas-navigation :s https://github.com/laminas/laminas-navigation/issues/28

**Comment by Ocramius** [comment]
Now fixed: https://github.com/laminas/laminas-dom/compare/2.10.0...2.11.0

Sorry for the noise :D

**Pull request merged**
